### PR TITLE
Edit profile: Add image

### PR DESCRIPTION
**Pull request by gguijarro-c-chwy**
Add image from Edit image page.

@nik We need to return the image URL on that call. Is it possible?

### CODE REVIEW

**Comment by gguijarro-c-chwy** [comment]
@n13  ^^

**Comment by n13** [comment]
As soon as it's uploaded, we can call get profile from our custom backend, and get the image url from that

**Review by n13 — APPROVED** [review]
LGTM

**Comment by n13** [comment]
Use this to update the profile after uploading the image:

  Future<Result<ProfileData, HyphaError>> getProfile(String accountName) async {

**Comment by gguijarro-c-chwy** [comment]
> Use this to update the profile after uploading the image:
> 
> Future<Result<ProfileData, HyphaError>> getProfile(String accountName) async {

Yeah, i implemented this. I was trying to avoid an extra call ;/

**Pull request merged**
