### PR TITLE
Feature/Enroll - On invite link

### PR DESCRIPTION
**Pull request by gguijarro-c-chwy**
image

### CODE REVIEW

**Comment by gguijarro-c-chwy** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>:exclamation: PR has more than 500 line changes </td>
    </tr>
  </tbody>
</table>



> Pull Request size seems relatively large. If Pull Request contains multiple changes, split each into separate PR will helps faster, easier review.
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 30ef7ca04d28793f6b9b8df0587873be1f82d684
</p>

**Review by n13 — APPROVED** [review]
UI looks great

Code LGTM - my main concern would be interference with other startup / initialization ways

- Does this work when there's no account - meaning when there's no account, we get this invite link, and process it as before, and auto-join the DAO as before. And this popup does then **not** show

- Can it interfere with other deep link actions - esr signing requests, push notifications?

- Is it cleared (I guess that yes it is)

Yeah so I guess I will need to test this with no account and with account and when both work it's good.

**Comment by n13** [comment]
One change  request - parse "daoName" field for the dao name, instead of "dao". "dao" is the id of the dao ... daoName is a string with the full name.

See here.
https://github.com/hypha-dao/hypha_wallet/issues/220

**Comment by n13** [comment]
DAO name in another PR

**Pull request merged**
